const {ccclass, property} = cc._decorator;

@ccclass
export default class ResourceManager extends cc.Component {
    @property({type:cc.SpriteFrame})
    sf_arrowBlue:cc.SpriteFrame = null;
    @property({type:cc.SpriteFrame})
    sf_arrowPink:cc.SpriteFrame = null;
    @property({type:cc.Prefab})
    pf_matchView:cc.Prefab = null;
    @property({type:cc.Prefab})
    pf_settlePanel:cc.Prefab = null;
    @property({type:cc.Prefab})
    pf_boy:cc.Prefab = null;
    @property({type:cc.Prefab})
    pf_blood:cc.Prefab = null;
    @property({type:cc.AudioClip})
    ac_attack:cc.AudioClip = null;
    @property({type:cc.AudioClip})
    ac_bu:cc.AudioClip = null;
    @property({type:cc.AudioClip})
    ac_win:cc.AudioClip = null;

    onLoad(){
        window.rs = this;
    }
}
